Update to some files

diff --git a/.github/workflows/bootstrap-backend.yml b/.github/workflows/bootstrap-backend.yml
--- a/.github/workflows/bootstrap-backend.yml
+++ b/.github/workflows/bootstrap-backend.yml
@@ -13,7 +13,7 @@ on:
         default: "devsecops-project1-tflocks"
 
 permissions:
-  id-token: write   # REQUIRED for GitHub OIDC to AWS
+  id-token: write
   contents: read
 
 jobs:
@@ -29,11 +29,29 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      # Fail fast if env secrets are missing
+      - name: Validate required environment secrets
+        shell: bash
+        run: |
+          set -euo pipefail
+          if [ -z "${{ secrets.AWS_ROLE_ARN_APPLY }}" ]; then
+            echo "ERROR: Environment 'dev' secret AWS_ROLE_ARN_APPLY is missing/empty."
+            exit 1
+          fi
+          if [ -z "${{ secrets.AWS_REGION }}" ]; then
+            echo "ERROR: Environment 'dev' secret AWS_REGION is missing/empty."
+            exit 1
+          fi
+
       - name: Configure AWS credentials (OIDC)
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN_APPLY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          audience: sts.amazonaws.com
+
+      - name: Verify AWS identity
+        run: aws sts get-caller-identity
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
